//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TVapimvcuygulama.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bloklar
    {
        public int BlokNo { get; set; }
        public string BlokAdi { get; set; }
        public Nullable<int> BlokSayisi { get; set; }
    }
}
