//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TVapimvcuygulama.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Kullanicilar
    {
        public int KullaniciNo { get; set; }
        [Required(ErrorMessage = "Boþ Geçilemez!!")]
        [Display(Name = "kullanici adý")]
        public string KullaniciAdi { get; set; }
        [Required(ErrorMessage = "Boþ Geçilemez!!")]
        [Display(Name = "Sifre")]
        [DataType(DataType.Password)]
        public string Sifre { get; set; }

        [Required(ErrorMessage = "Boþ Geçilemez!!")]
        [Display(Name = "MatchSifre")]
        [DataType(DataType.Password)]
        [NotMapped]
        [Compare("Sifre", ErrorMessage = "sifreler eþleþmiyor tekrar deneyiniz!!")]

        public string MatchSifre { get; set; }
    }
}
