//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TVapimvcuygulama.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class apimvcuygulamaEntities3 : DbContext
    {
        public apimvcuygulamaEntities3()
            : base("name=apimvcuygulamaEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bloklar> Bloklars { get; set; }
        public virtual DbSet<Görevler> Görevler { get; set; }
        public virtual DbSet<Hizmetler> Hizmetlers { get; set; }
        public virtual DbSet<Kullanicilar> Kullanicilars { get; set; }
        public virtual DbSet<Personeller> Personellers { get; set; }
        public virtual DbSet<Plazalar> Plazalars { get; set; }
    }
}
