//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TVapimvcuygulama.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plazalar
    {
        public int PlazaNo { get; set; }
        public string PlazaAdi { get; set; }
        public Nullable<int> PlazaKatSayisi { get; set; }
        public string Il { get; set; }
        public string Ilce { get; set; }
    }
}
